### ISSUE TITLE
Allow for Honors courses

### ISSUE THREAD

**Issue by KyraWayne** [COEN174/MainProject#20]
@jkingsman or @Pillager225 could you make the system account for honors courses which are equally valid, it should just ignore if ever there is an H at the end. i.e. ENGL001H, AMTH108H. Working on things assigned to me

**Comment by jkingsman** [comment]
I'm gonna reopen this and take care of this now.

**Comment by KyraWayne** [comment]
no need it's a non-issue. for the ones that have their requirements listed in the json, it works fine thanks to taking in substrings. should have checked first. carry on.

**Comment by jkingsman** [comment]
Whoops; didn't see your comment. Well, we identify and remove the H now haha.
