### ISSUE TITLE
Add listener on text entry and rework submission code

### ISSUE THREAD

**Issue by jkingsman** [COEN174/MainProject#32]
Set it up however it makes the most sense (e.g. form, couple of listeners, etc.) so that you can strike enter in the text area or hit the submit button and have the submission go through, clear the area, and refocus.

**Comment by RyanLoringCooper** [comment]
I'll put my work to fix this issue in a branch called FixTextEntry.

**Comment by RyanLoringCooper** [comment]
Seems like there is no issue in the master branch at this time. Enter or submit will make it work. I think I am missing something. There is no text entry div, but instead the old form submit. Possibly this needs a look from @KyraWayne? 

@KyraWayne is master current with the changes you showed us during our meeting on 10/30/2016? If not, could you make a branch with the changes so I can use that branch to work on getting enter to work with the text entry thingy?

**Comment by RyanLoringCooper** [comment]
Ah nevermind, I found the edits in an old commit from master. I didn't choose those edits in the merge I did with table-branch. My mistake.
