### ISSUE TITLE
Percentages are not accurate

### ISSUE THREAD

**Issue by KyraWayne** [COEN174/MainProject#36]
Since consolidating numerous requirements under one title (i.e. Educational Enrichment counts for 3-4 requirements) the percentage at the top is made inaccurate (out of 47 rather than 51). We need to go through and make it so that Educational Enrichment counts for 4x its current amount, and allow for proportional progress updates, and do the same for any other consolidated requirements.

**Comment by jkingsman** [comment]
Does it really count for more than one requirement though? Seems to me that it really only counts for one, although satisfying it can consist of multiple classes -- you can't have partial completion of EEE though.

**Comment by KyraWayne** [comment]
@jkingsman you are right we did talk about this last night-- might be reconsidering decision to consolidate then in general but for the sake of tomorrow's demo we'll keep it as is

**Comment by jkingsman** [comment]
Educational enrichment now doesn't increment percentage as is correct; closing.
