### ISSUE TITLE
Mobile is a mess.

### ISSUE THREAD

**Issue by jkingsman** [COEN174/MainProject#38]
Just view it on a phone and you'll see.

**Comment by jkingsman** [comment]
I suspect `float`ing is causing issues

**Comment by KyraWayne** [comment]
overflow:hidden helps solve this issue. keeping this open for when we create secondary dropdowns

**Comment by jkingsman** [comment]
Great - let's close this for now since this isn't on the roadmap -- I was perhaps a bit too zealous with marking it down as such a dramatic issue :P  Sorry about that.
