### ISSUE TITLE
Core requirements need to be updated in JSON

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#39]
We need to complete the JSON entries for the core requirements. I have created JSON entries for all the requirements, and they just need the classes put into their [ ] entry. Sorry I don't know the proper terminology, but take a look at requirements.json to see what I mean.

**Comment by RyanLoringCooper** [comment]
I added more requirements to the json file, which leaves CNI1, CNI2, STS, ELSJ, and Religious_Studies_1 as classes that still need requirements. The SCU Core Guide does not display classes for CNI1, CNI2, or Religious_Studies_1, so maybe it is worth using another source to determine what satisfies those classes, such as scu classes or course avail.

**Comment by jkingsman** [comment]
This is closed now, right @KyraWayne?
