### ISSUE TITLE
need div for educational enrichment classes and classes that satisfy nothing

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#52]
title says it all. I mentioned this issue in pull request #51

**Comment by RyanLoringCooper** [comment]
So how are we going to display these classes?

**Comment by jkingsman** [comment]
I can get something rough put in later today and @KyraWayne can make it look bueno.

**Comment by jkingsman** [comment]
Do we have storage for these classes built yet (like, going into local storage)? Saving/restoring/etc?

**Comment by RyanLoringCooper** [comment]
Yes. See the function putInEducationalEnrichment in helpers.js.

**Comment by RyanLoringCooper** [comment]
Well that just does saving. I did not write it to restore. I can do that later if it is not done by then.
