### ISSUE TITLE
Scheduling dropdowns do not have their hint when the page is loaded.

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#54]
You can get them to have their hint by hitting enter or update in text area when it has valid input. 

The dropdowns should say Quarter when the page is first loaded. I am not sure why they do not do this by default, but this functionality was broken in one of the more recent merges with master. I'll try to find which one specifically.

**Comment by jkingsman** [comment]
Right away I can see on https://github.com/COEN174/MainProject/pull/51/files#diff-103715cf0e3db43f218c7235fd2a18fbL86 on line 86 in your `helpers.js` that it's doing a check on a value that doesn't exist -- the dropdown will never have a selected value of 'selected'; the class is scheduled if and only if the dropdown _doesn't_ have a vale of 'notselected'. I will look more in depth later today but I think that may be your main issue.

**Comment by RyanLoringCooper** [comment]
I made that edit on line 86 because originally that was the line that was making all of the classes yellow, even when they were unscheduled. It was because it was hitting the else because it wasn't equal to 'notselected' and the else was making it yellow. Master currently has the same issue.

**Comment by jkingsman** [comment]
Master currently works fine for me. Try clearing your localstorage with `localstorage.requirements = {}` in the console then hitting Clear Form.

Edit: Also works fine in FF.

**Comment by RyanLoringCooper** [comment]
You are right. My mistake. I have fixed this issue in moreReqs.
