### ISSUE TITLE
Changes to localStorage do not update UI

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#55]
even when buildList() and refreshPage() are called after changes to localStorage. Maybe I am missing something? Take a look at it please when you get some time.

**Comment by jkingsman** [comment]
I'll work through these issues this afternoon. I'm confident there's an existing way to do this; I think calling `refreshPage()` directly may be saving the UI first which would overwrite changes to the backend. My gut says doing everything that `refreshPage()` does except for saving should work but I'll put together a solid function call list that we can use to display data state in the UI and package it a function in master.

**Comment by jkingsman** [comment]
Actually if you're in merge hell, I'll just add it as a PR onto your existing branch and you can do with that as you please.

**Comment by RyanLoringCooper** [comment]
I am do not think I am in merge hell because it can be merged with master as is. Feel free to modify moreReqs because I won't work on it for the rest of today.

**Comment by jkingsman** [comment]
Dope; sounds good. I'll work in master to get that set up then and report back here once I've got a good solution for backpopulating the UI.

**Comment by jkingsman** [comment]
For posterity's sake, the function to update the UI with backend data is `drawFromData()`.
