### ISSUE TITLE
Select menues are reset after textbox entry is used to update data

### ISSUE THREAD

**Issue by RyanLoringCooper** [COEN174/MainProject#56]
There needs to be some code put in around line 30 in classloader.js to check if a class is selected for a satisfied requirement. Possible use local storage data to determine this instead of ui.

**Comment by RyanLoringCooper** [comment]
It also does this to the scheduled date dropdown.

**Comment by jkingsman** [comment]
I'm not seeing this replicate for me -- could you provide a process to replicate, please?

**Comment by jkingsman** [comment]
I think we fixed the issue, right? Feel free to close if we did

**Comment by RyanLoringCooper** [comment]
This is fixed, but classes are reset. What did we do to fix this? The procedure to see the bug is to select a class for a requirement, and then enter a class into the textbox.
