### ISSUE TITLE
1:1 classes don't need the class selection dropdown displayed

### ISSUE THREAD

**Issue by jkingsman** [COEN174/MainProject#60]

**Comment by jkingsman** [comment]
@KyraWayne I'm going to wait until you get 1-to-1-reqs merged since this will use the same logic

**Comment by KyraWayne** [comment]
Currently happy with how it looks! @Pillager225 @jkingsman let me know what you think

**Comment by jkingsman** [comment]
Can you push your branch and open a PR?

**Comment by jkingsman** [comment]
I did a review; looks pretty good. Just a few minor nits then we're good to merge.

**Comment by KyraWayne** [comment]
I saw! On it
