### ISSUE TITLE
Complete Remaining Req Lists

### ISSUE THREAD

**Issue by KyraWayne** [COEN174/MainProject#73]
C&I 1, C&I 2, and STS

**Comment by jkingsman** [comment]
I can load these in - where should they be drawn from/do you have a link to the source of truth for these?

**Comment by jkingsman** [comment]
Oh wait I see you assigned this - sorry; didn't mean to step on your toes.

**Comment by KyraWayne** [comment]
@jkingsman we might need to reverse ignoring letters after the three numbers in a req since a lot of the ELSJ courses have letters like EL or A at the end

**Comment by jkingsman** [comment]
Hmmm and without the EL or A they're specifically a different class?

**Comment by KyraWayne** [comment]
yes, it will trigger a different requirement or place it under EE

**Comment by jkingsman** [comment]
Hrm. That's a PitA. Can we flag this issue as a todo item that won't be done for the demo?

**Comment by KyraWayne** [comment]
I'm fine with that!

**Comment by jkingsman** [comment]
Great; let's do that then. We can still merge in all the new reqs but just keep this issue open so we know we need to work on that.

**Comment by RyanLoringCooper** [comment]
I believe Jack and I discussed this before. The EL or A will be ignored, but the class can still be used to check off the requirement so long as the EL and A are left off of the classes in the JSON. I took that approach with other requirements already.

**Comment by KyraWayne** [comment]
but this makes for completely different courses that do not double dip. For example, SPAN022 (intermediate spanish) is not inherently an ELSJ but SPAN022EL is.

**Comment by RyanLoringCooper** [comment]
Ok. I agree, but let's not forget to merge before tomorrow.

**Comment by jkingsman** [comment]
This is closed out with Kyra's 61bf003715c80411c69b82daf86616fb4eba10f4.
